spring.application.name=leave-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/leave_management
spring.datasource.username=root
spring.datasource.password=90108215

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080